runtime: nodejs18  # or your preferred Node.js version

env_variables:
  NODE_ENV: "production"
  # Add other production environment variables here

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto 