steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/react-app:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/react-app:$SHORT_SHA'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://focus-music-app-368754647823.us-central1.run.app'
      - '.'

  # Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--service-account'
      - 'harry-gillen-builder@appspot.gserviceaccount.com'

  # Cleanup old images (keep last 5 versions)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container images list-tags gcr.io/$PROJECT_ID/react-app \
          --format="get(digest)" --sort-by=~timestamp \
          --limit=unlimited | tail -n +6 | \
        xargs -I {} gcloud container images delete \
          gcr.io/$PROJECT_ID/react-app@{} --quiet

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/react-app:latest'
  - 'gcr.io/$PROJECT_ID/react-app:$SHORT_SHA'

serviceAccount: 'harry-gillen-builder@appspot.gserviceaccount.com'