steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app', '.']
    env:
      - 'NODE_ENV=production'
      - 'REACT_APP_API_URL=${_REACT_APP_API_URL}'
      - 'AUDIO_STORAGE_PATH=${_AUDIO_STORAGE_PATH}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-app'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _REACT_APP_API_URL: 'https://your-production-url.app'
  _AUDIO_STORAGE_PATH: 'https://storage.googleapis.com/react-app-assets/audio'

images:
  - 'gcr.io/$PROJECT_ID/react-app'