steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app', '.']
    env:
      - 'NODE_ENV=production'
      - 'REACT_APP_API_URL=${_REACT_APP_API_URL}'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY  # Specify logging option
  machineType: 'N1_HIGHCPU_8'  # Optional: specify machine type for faster builds

substitutions:
  _REACT_APP_API_URL: 'https://focus-music-app-368754647823.us-central1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/react-app'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/your-service-account@$PROJECT_ID.iam.gserviceaccount.com'